### ISSUE TITLE
Can not reproduce cifar10 results of cnn model

### ISSUE THREAD

**Issue by TheSunWillRise** [ftramer/Handcrafted-DP#1]
Hi,
I run "python3 cnns.py --dataset=cifar10 --batch_size=1024 --lr=1 --noise_multiplier=1.54" with end-to-end cnn model for 30 epochs (eps=3) and got test acc 48.05%, which is much worse than the result reported in your paper (59.2% ).
Is there any thing wrong?

**Comment by ftramer** [comment]
Thanks for raising this issue.
I presume that you're using the latest version of Opacus? 
There has been a major change in how Opacus handles virtual batches between version 0.9 (which this repo assumes) and the current version.

To use the latest version of Opacus you should:

1) remove the `optimizer.zero_grad()` call here: https://github.com/ftramer/Handcrafted-DP/blob/2a1c3a84ee54b6acceca19ebb8fc28e749c4222b/train_utils.py#L33
2) call `optimizer.zero_grad()` immediately after `optimizer.step()` here: https://github.com/ftramer/Handcrafted-DP/blob/2a1c3a84ee54b6acceca19ebb8fc28e749c4222b/train_utils.py#L41

**Comment by TheSunWillRise** [comment]
That works. Thank you.

**Comment by ftramer** [comment]
Just a note that this repository has been updated to now work with the latest version of Opacus.
As a result, things will break if you use Opacus v0.9 or earlier.
