### ISSUE TITLE
 Hyper-parameters search 

### ISSUE THREAD

**Issue by AliShahin** [ftramer/Handcrafted-DP#3]
Dear Florian,

I wonder if you could share any script for the  hyper-parameters search that you have done for your Table 12 please?

**Comment by ftramer** [comment]
Sorry for the slow response.
I've added the scripts I used for CIFAR-10 here: https://github.com/ftramer/Handcrafted-DP/tree/main/scripts
The ones for MNIST and F-MNIST are basically the same, except that the dataset size is 60K instead of 50K.
