### ISSUE TITLE
[Bug] --early-stop should be declared differently

### ISSUE THREAD

**Issue by skat00sh** [ftramer/Handcrafted-DP#5]
Hello Prof. Tramer (@ftramer ),
One of the flags in `cnns.py` should be declared differently. 
Right now it's like 
```Python
 parser.add_argument('--early_stop', type=bool, default=True)
```
But when passing the command line argument like `python cnns.py --early-stop=False` it would take the value as `True` since `False` is a non-empty string.
I would suggest doing it like
```Python
  parser.add_argument("--early_stop", action="store_false")
```
I can make a PR for the issue since I already have it in my forked version of the repo.

I've been using this repo for a few weeks now and I've also included methods to resume training and strore best_model and store checkpoints every Nth EPOCH. 
If the development on this repo is still active I'd like to contribute to that. 

Thank you for your work, it has been really helpful so far.

**Comment by ftramer** [comment]
Thanks for noticing this, it is indeed a bug.
I'm happy to merge a PR that fixes this.

**Comment by skat00sh** [comment]
Thank you for the prompt response @ftramer 
PR Done! 
Do you think this repo needs other features like the ones I suggested above?
I'll be happy to create PRs for those as well

**Comment by ftramer** [comment]
The repo isn't being developed further at the moment so I'd rather leave it in the original state which I know reproduces the results from the paper.
If there's interest in new features in the future, definitely!
